STOCK_TICKER_TEA = "TEA"
STOCK_TICKER_POP = "POP"
STOCK_TICKER_ALE = "ALE"
STOCK_TICKER_GIN = "GIN"
STOCK_TICKER_JOE = "JOE"

STOCK_BUY_CODE = 1
STOCK_SELL_CODE = 2

STOCK_BUY = "Buy"
STOCK_SELL = "Sell"